modLoader="javafml"
loaderVersion="*"
license="MIT"

[[mods]]
modId = "mixinextras"
version = "${extrasversion}"
displayName = "MixinExtras"
description = '''
Companion library to Mixin with lots of features to improve the compatibility and concision of your mixins!
'''
authors = "Llamalad7"
displayURL = "https://github.com/Llamalad7/MixinExtras"
displayTest="IGNORE_SERVER_VERSION"