name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [8-jdk, 11-jdk, 16-jdk, 17-jdk]
    runs-on: ubuntu-22.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - run: ./gradlew build --stacktrace